### ISSUE TITLE
Allow .vue Components (and other) to be imported as StoryblokComponent

### ISSUE THREAD

**Issue by fiveam-lukas** [storyblok/storyblok-astro#357]
### Description

As a developer using Storyblok with Astro, but with Vue (and/or Svelte) Frontend Library, I want to be able to write storyblok Components as .vue or .svelte Files. Right now in Astro, when initiliasing storyblok with its Components, these component paths get suffixed with `.astro`.

### Suggested solution or improvement

I would be great to auto-detect the components type by its file suffix. So we could use the full astro potential by being able to use any frontend library and even mix them if needed.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fiveam-lukas** [comment]
```typescript
storyblok({
    accessToken: env.STORYBLOK_TOKEN,
    components: {
      page: "storyblok/Page",
      simpleText: "storyblok/SimpleText",
    }
  }),
``` 

Currently these paths in `components` would be prefixed with `src/` and suffixed with `.astro`, leading to the unability to use a `storyblok/SimpleText.vue` Component

**Comment by manuelschroederdev** [comment]
Hey @fiveam-lukas,

thanks for opening the issue. The integration was designed like this on purpose because Vue/Svelte/React/... components would require a [client directive](https://docs.astro.build/en/reference/directives-reference/#client-directives). 

You can implement such components as shown in the [Astro SDK Demo](https://stackblitz.com/edit/astro-sdk-demo?file=package.json).

I'd be happy to consider a better solution, do you have any suggestions? 🙂

By the way, `src` folder can be changed using the `componentsDir` option. 😉

**Comment by manuelschroederdev** [comment]
Hey @fiveam-lukas, what do you think?
