### ISSUE TITLE
Make Storyblok Bridge disabled by default

### ISSUE THREAD

**Issue by edv-ns** [storyblok/storyblok-astro#48]
## Context

According the current documentation: https://github.com/storyblok/storyblok-astro#using-the-storyblok-bridge:
> The Storyblok Bridge is automatically activated by default.

Code:
https://github.com/storyblok/storyblok-astro/blob/d45878d9f1deef23a297931847f1776fbc332d7c/lib/index.js#L57

But that is in fact seems wrong way to approach it, as the users of `storyblok-astro` package may risk having redundant `https://app.storyblok.com/f/storyblok-v2-latest.js` script loaded even if they do not use it (that happened for us once 😄 ). It seems package users must add `bridge: false` explicitly to disable this script in production build targets.

How it works now (opt-out):
```
bridge: true | undefined,          // load script
bridge: false,                     // skip script
```

IMHO, it is much more intuitive to go (opt-in):
```
bridge: true,                      // load script
bridge: false | undefined,         // skip script
```

Because this way the bridge script is loaded ONLY if it is explicitly needed.

## TODO
 - Change bridge script loading to be disabled by default

**Comment by manuelschroederdev** [comment]
Thank you! I agree with your reasoning. We'll look into it. 🙂

**Comment by manuelschroederdev** [comment]
Hey @edv-ns, thanks again for your suggestion.

My colleagues and I discussed it but decided against implementing it in this integration. Disabling the bridge by default would create an inconsistency with all our other SDKs. As using the bridge is the most common scenario, we decided to employ an opt-out strategy. If we change it for the Astro SDK, we would have to change it everywhere. Since it can easily be disabled, I'm closing this issue.
