### ISSUE TITLE
How to use `useStoryblokApi` inside Vue components?

### ISSUE THREAD

**Issue by romanhrynevych** [storyblok/storyblok-astro#728]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

---

## Expected Behavior

When importing `useStoryblokApi` from `@storyblok/astro` inside vue components to fetch dynamic content want to work correctly

## Current Behavior

Receive such error

<img width="427" alt="image" src="https://github.com/storyblok/storyblok-astro/assets/82209198/596867bd-c142-43af-ae93-534cb5da9666">

## Steps to Reproduce

1. Create astro project
2. add @storyblok/astro integration
3. call `useStoryblokApi` inside Vue components

Editional:

If I need to add `@storyblok/vue` integration, how can I configure it inside `vue()` plugin inside `astro.config.mjs`?

**Comment by schabibi1** [comment]
Hi @romanhrynevych 
To fetch dynamic content in the Vue (or other frameworks) component, you need to import and call `useStoryblokApi` in `pages/index.astro` and `page/[slug].astro` as you can see from our [live demo](https://stackblitz.com/edit/astro-sdk-demo?file=src%2Fpages%2Findex.astro%3AL7).

- [In `pages/index.astro`](https://stackblitz.com/edit/astro-sdk-demo?file=src%2Fpages%2Findex.astro%3AL7)
- [In `pages/[slug].astro` ](https://stackblitz.com/edit/astro-sdk-demo?file=src%2Fpages%2F[slug].astro)

To fetch dynamic data in Vue component, you can use `blok` prop to fetch the path you can find in the draft JSON.
For example, to fetch `headline` in the `storyblok/vue/Counter.vue` component, you can fetch with `blok.headline` as you see in the screenshot.
<img width="1512" alt="Screenshot 2024-03-25 at 14 13 33" src="https://github.com/storyblok/storyblok-astro/assets/25793187/13d3910e-67d3-42b9-8bc9-18b7d4979607">

`blok` hods the rest of the data path form the beginning of this story as you can see in the [`storyblok/VueCounter.astro`](https://stackblitz.com/edit/astro-sdk-demo?file=src%2Fstoryblok%2FVueCounter.astro)

```javascript
---
import { storyblokEditable } from '@storyblok/astro';
import Counter from './vue/Counter.vue';

const { blok } = Astro.props// ⬅️
---

<div {...storyblokEditable(blok)}>
  <Counter blok={blok} client:visible />
</div>
```

You don't need to install @storyblok/vue additionally.

**Comment by schabibi1** [comment]
Feel free to re-open if the solution I provided doesn't solve your issue. Closing this issue as it worked on my end when I tested and on our live demo environment.

**Comment by romanhrynevych** [comment]
Yes, but issue is in another place, how can we make API call to Storyblok inside Vue component not astro. For example you have filters on Vue side, and want after select change -> update Vue list from storyblok API, how to do such logic?

**Comment by schabibi1** [comment]
@romanhrynevych Thanks for adding more details.
In your case, the short answer is:
- You'll need to additionally install [@storyblok/vue](https://github.com/storyblok/storyblok-vue)
- `vue()` can be added to `integrations": []` 

```js
// astro.config.mjs
export default defineConfig({
  integrations: [
    vue(),
    storyblok({
      accessToken: "your_access_token",
     // the rest of config
    }),
  ],
// the rest of config
```

- You can initialize to provide a `storyblokApi` object in your app from @storyblok/vue at Vue components (i.e. `CasesGrid.vue`, `Counter.vue` etc) [(An example below on the Visual Editor)](https://www.loom.com/share/06a9206ebcf24222988068bb0cf24e2d?sid=018432c0-49d9-4290-a5ee-4f87379d8769)

```vue
<template>
  <!-- counter example from the live demo -->
  <div class="counter">
    <!-- ... -->
  </div>
  <div class="counter-message">{{ blok.headline }}</div>
  <!-- an array of items fetched from Storyblok Content Delivery API -->
  <ul>
    <li v-for="item in blok.item_list" :key="item._uid">
      {{ item }}
    </li>
  </ul>
  <!-- log fetched data from a story (page) -->
  <p>{{JSON.stringify(story)}}</p>
</template>

<script setup>
import { ref, createApp } from "vue";
import { StoryblokVue, apiPlugin } from "@storyblok/vue";
import { useStoryblok } from "@storyblok/vue";

const app = createApp({});

app.use(StoryblokVue, {
  accessToken: "your_access_token",
  use: [apiPlugin],
});

<!-- initialize here -->
const story = await useStoryblok('home', { version: 'draft' });

defineProps({ blok: Object });
const count = ref(0);
const add = () => (count.value = count.value + 1);
const subtract = () => (count.value = count.value - 1);
</script>
```

I'm not 100% sure if I understood how exactly you wanted to filter the list and where you wanted to make changes to the list.
But a [multi-option field-type (see our docs for details)](https://www.storyblok.com/docs/schema-configuration) can create an array to list items. And you can fetch this field-type content and dynamically change it on the Visual Editor.
Does it cover what you asked? If I missed something from your additional info, please let me know.

Astro initializes or loads Storyblok APIs you use through our SDKs at build time.
Other libraries and frameworks load them at the run time.
`.astro` files and `.vue` files (components) are separate environments. Mostly, people go with Astro because they want to benefit from shipping no JS from the rendered pages.
