### ISSUE TITLE
Could the StoryBlok instance provide an `isPreview` flag?

### ISSUE THREAD

**Issue by nathobson** [storyblok/storyblok-astro#795]
### Description

Unless I've missed it, there doesn't seem to be a way to detect if the site is being loaded within the StoryBlok editor from the StoryBlok instance.

My current use case is that my whole site is SSRed. In my mind, this should mean that I could run the editor and the front-end from a single deployment of the site.

The current documentation ([link](https://www.storyblok.com/tp/create-a-preview-environment-for-your-astro-website#deploying-the-preview-version-on-vercel)) seems built around the assumption that you'd want the editor SSRed and the front-end built out statically. The solution there is to have two separate identical deployments but with a single env var changed between the two to flag the story version to load.

### Suggested solution or improvement

If the SKD provided a flag for if the current instance is loaded within the editor or not then you could have something like this:

```
---
//  index.astro
import { useStoryblokApi } from "@storyblok/astro";
import StoryblokComponent from "@storyblok/astro/StoryblokComponent.astro";
import BaseLayout from "../layouts/BaseLayout.astro";

const storyblokApi = useStoryblokApi();
const { data } = await storyblokApi.get("cdn/stories/home", {
  version: storyblokApi.isPreview ? 'draft' : 'published',
});

const story = data.story;
---

<BaseLayout>
  <StoryblokComponent blok={story.content} />
</BaseLayout>
```

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by dipankarmaikap** [comment]
Hi @nathobson 

If you're using SSR, you can easily determine if your site is inside Storyblok by following these steps:
```
const inStoryBlokEditor =
  Astro.url.searchParams.has('_storyblok') &&
  Astro.url.searchParams.has('_storyblok_c')
  
```
You can `console.log(Astro.url)` to see the numerous query parameters added when you're in the visual editor. Additionally, you can refer to this guide on [how to verify the preview query parameters of the visual editor](https://www.storyblok.com/faq/how-to-verify-the-preview-query-parameters-of-the-visual-editor) if needed.

Although if you're using SSR and can handle the `draft` and `published` version from one deployment, our tutorial demonstrates two different deployments because it provides more control. Even if you're using full SSR, you may find adding caching on top of this single deployment a bit troublesome. However, if you want to do it, you can determine if you're in the Storyblok visual editor as I shared.

**Comment by schabibi1** [comment]
Closing this issue for now but please feel free to re-open the issue if you still have further questions/issues when you test the solution from above.
